[package]
name = "tonic-error"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.10"
serde = {version = "1.0.137", features = ["derive"]}
serde_json = "1.0.82"
thiserror = "1.0.31"
tonic = "0.7"
tonic-error-impl = {path = "tonic-error-impl" }

[workspace]
members = ["tonic-error-impl"]
